SUPABASE_URL = "https://obzztuakskphspfjouvv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ienp0dWFrc2twaHNwZmpvdXZ2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzY5MjA2OCwiZXhwIjoyMDY5MjY4MDY4fQ.xSKPwny5b6DXxKNBtWSZ1JJQta3aqdNYfnvTI4xQ0p0"
APP_PASSWORD = "Mahira_123"
