SUPABASE_URL = "https://obzztuakskphspfjouvv.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ienp0dWFrc2twaHNwZmpvdXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2OTIwNjgsImV4cCI6MjA2OTI2ODA2OH0.kFZsRSdyF9aQ26_zOTKRpZCnz3dn5vqw5MqtoJPhwL0"
APP_PASSWORD = "Mahira_123"